### ISSUE TITLE
"The requested resource does not support http method `POST'."

### ISSUE THREAD

**Issue by kayceeec** [anthonws/MDATP_PoSh_Scripts#9]
Hi,

I am trying to run the code and get the following error
"The requested resource does not support http method `POST'."

any advise on how to mitigate this?

**Comment by anthonws** [comment]
What script?

**Comment by kayceeec** [comment]
Please find below

https://github.com/anthonws/MDATP_PoSh_Scripts/blob/master/API/API_Tag_Sample.ps1

<-- REDACTED -->

**Comment by anthonws** [comment]
@kayceeec  Please do not paste private information like you tenant Id, App ID, Secret. Please change the secret to that App immediately!!

I've tested the script and it is running perfectly. Had no issues.

Please review your App in Azure AD and the instructions of the script.

Thanks,
anthonws.

**Comment by kayceeec** [comment]
Oh pasted the un edited version 

Thanks any specific pointers as to what needs to be taken into consideration or what was missed Please delete the file as I am unable to access it.

**Comment by anthonws** [comment]
Like pointed out previously . Script has no issues.
